In [1]:
import numpy as np

In [2]:
np.__version__

'2.3.1'

## Create & Read

#### 1D Array

In [3]:
arr1 = np.array([1,2,3,4,5])
arr1

array([1, 2, 3, 4, 5])

In [4]:
type(arr1)

numpy.ndarray

In [5]:
arr1.shape

(5,)

In [6]:
arr1.dtype

dtype('int64')

In [7]:
arr1.ndim

1

In [8]:
arr1.size

5

#### 2D Array

In [9]:
arr2 = np.array([[1, 4, 5], [6, 7, 4]])
arr2

array([[1, 4, 5],
       [6, 7, 4]])

In [10]:
arr2.ndim

2

In [12]:
arr2.shape # (row, column)

(2, 3)

In [13]:
arr2.dtype

dtype('int64')

In [14]:
arr2.size

6

#### 3D Array

In [20]:
arr3 = np.array([[[1, 4, 5], [6, 7, 4]], [[3, 5, 4], [5, 8, 7]], [[3, 5, 4], [5, 8, 7]]])

In [21]:
arr3

array([[[1, 4, 5],
        [6, 7, 4]],

       [[3, 5, 4],
        [5, 8, 7]],

       [[3, 5, 4],
        [5, 8, 7]]])

In [22]:
arr3.ndim

3

In [23]:
arr3.shape # (number of layer, 2 row for each layer, 3 column for each layer)

(3, 2, 3)

In [24]:
arr3.size

18

## Create random array

In [25]:
randomArr = np.random.rand(3, 2, 3)
randomArr

array([[[0.69678412, 0.98287336, 0.07983064],
        [0.50591535, 0.2029241 , 0.3960658 ]],

       [[0.25342235, 0.7086035 , 0.73095155],
        [0.64618832, 0.52947044, 0.70645101]],

       [[0.67252643, 0.78643974, 0.07820759],
        [0.6678366 , 0.94360978, 0.55209619]]])

In [26]:
randomArr.dtype

dtype('float64')

In [27]:
zeroes = np.zeros((3,2,3))
zeroes

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [28]:
zeroes.ndim

3

In [29]:
full = np.full((3, 2, 3), 8)
full

array([[[8, 8, 8],
        [8, 8, 8]],

       [[8, 8, 8],
        [8, 8, 8]],

       [[8, 8, 8],
        [8, 8, 8]]])

In [30]:
ones = np.ones((3,2,3))
ones

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [31]:
arr3[0]

array([[1, 4, 5],
       [6, 7, 4]])

In [32]:
arr3[0][0]

array([1, 4, 5])

In [34]:
arr3[0][0][2]

np.int64(5)

In [35]:
arr3[0:2]

array([[[1, 4, 5],
        [6, 7, 4]],

       [[3, 5, 4],
        [5, 8, 7]]])

In [36]:
arr3[-1]

array([[3, 5, 4],
       [5, 8, 7]])

In [38]:
arr3[1][0][1]

np.int64(5)

In [39]:
arr3[1,0,1]

np.int64(5)

## Update & Delete

In [40]:
a1 = np.random.rand(2,3,2)
a2 = np.random.rand(2,3,2)

In [41]:
a1

array([[[0.76891146, 0.21634236],
        [0.73145533, 0.66776055],
        [0.07588717, 0.33099834]],

       [[0.40671445, 0.18518037],
        [0.9764628 , 0.31475044],
        [0.05366157, 0.22737451]]])

In [42]:
a2

array([[[0.37170866, 0.98472954],
        [0.18363894, 0.87969179],
        [0.10979974, 0.09049611]],

       [[0.71395316, 0.04259896],
        [0.26668336, 0.92833989],
        [0.7689645 , 0.28382683]]])

#### Basic Math Operations

In [43]:
np.add(a1, a2)

array([[[1.14062012, 1.2010719 ],
        [0.91509428, 1.54745234],
        [0.18568692, 0.42149445]],

       [[1.1206676 , 0.22777933],
        [1.24314616, 1.24309033],
        [0.82262607, 0.51120134]]])

In [44]:
np.subtract(a1, a2)

array([[[ 0.3972028 , -0.76838718],
        [ 0.54781639, -0.21193124],
        [-0.03391257,  0.24050223]],

       [[-0.30723871,  0.14258142],
        [ 0.70977943, -0.61358945],
        [-0.71530293, -0.05645232]]])

In [45]:
np.divide(a1, a2)

array([[[2.06858632, 0.21969724],
        [3.98311671, 0.75908467],
        [0.69114161, 3.65759758]],

       [[0.56966545, 4.34706352],
        [3.66150621, 0.33904656],
        [0.0697842 , 0.80110295]]])

In [47]:
np.multiply(a1, a2)

array([[[0.28581105, 0.21303871],
        [0.13432368, 0.58742347],
        [0.00833239, 0.02995406]],

       [[0.29037506, 0.00788849],
        [0.26040638, 0.29219539],
        [0.04126384, 0.06453499]]])

In [57]:
np.sqrt(25)

np.float64(5.0)

In [58]:
np.abs(-2)

np.int64(2)

In [59]:
np.power(2,8)

np.int64(256)

In [60]:
np.log(25)

np.float64(3.2188758248682006)

In [61]:
np.min(a1)

np.float64(0.053661571403540775)

In [62]:
np.max(a2)

np.float64(0.9847295377682324)

#### Update

In [63]:
arr3

array([[[1, 4, 5],
        [6, 7, 4]],

       [[3, 5, 4],
        [5, 8, 7]],

       [[3, 5, 4],
        [5, 8, 7]]])

In [64]:
arr3[0,0,2] = 500

In [65]:
arr3

array([[[  1,   4, 500],
        [  6,   7,   4]],

       [[  3,   5,   4],
        [  5,   8,   7]],

       [[  3,   5,   4],
        [  5,   8,   7]]])

In [66]:
arr3.sort()
arr3

array([[[  1,   4, 500],
        [  4,   6,   7]],

       [[  3,   4,   5],
        [  5,   7,   8]],

       [[  3,   4,   5],
        [  5,   7,   8]]])

In [67]:
# Reshape
arr3.shape

(3, 2, 3)

In [68]:
arr3_reshape = arr3.reshape([2,3,3])
arr3_reshape

array([[[  1,   4, 500],
        [  4,   6,   7],
        [  3,   4,   5]],

       [[  5,   7,   8],
        [  3,   4,   5],
        [  5,   7,   8]]])

In [69]:
arr3_reshape.shape

(2, 3, 3)

In [70]:
arr3_reshape = arr3.reshape([2,3,-1])
arr3_reshape

array([[[  1,   4, 500],
        [  4,   6,   7],
        [  3,   4,   5]],

       [[  5,   7,   8],
        [  3,   4,   5],
        [  5,   7,   8]]])

#### Appending & Inserting

In [71]:
zeroes

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [73]:
# create a new array
new_array = np.ones((3,2,3))
new_array

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [74]:
appd = np.append(zeroes, new_array, axis=0)
appd

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

# Insert 

In [75]:
zeroes

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [76]:
new_array

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [77]:
inserted_array = np.insert(zeroes, 1, new_array, axis=0)

In [78]:
inserted_array

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

## Delete

In [79]:
arr4 = np.random.rand(3,2,3)
arr4

array([[[1.20361367e-01, 5.26119355e-01, 1.99996215e-04],
        [7.54723245e-01, 2.23908337e-01, 8.68165341e-01]],

       [[9.91154732e-01, 9.71131099e-02, 6.57001123e-02],
        [9.73087599e-01, 4.43685614e-01, 4.59339077e-01]],

       [[7.61629421e-01, 8.00635886e-01, 4.47171173e-01],
        [1.46097191e-01, 8.51099820e-01, 6.94569262e-01]]])

In [81]:
# delete the array
arr5 = np.delete(arr4, 0, axis=1)
arr5

array([[[0.75472325, 0.22390834, 0.86816534]],

       [[0.9730876 , 0.44368561, 0.45933908]],

       [[0.14609719, 0.85109982, 0.69456926]]])

In [82]:
np.save('new_array', arr5)

In [84]:
np.load('new_array.npy')

array([[[0.75472325, 0.22390834, 0.86816534]],

       [[0.9730876 , 0.44368561, 0.45933908]],

       [[0.14609719, 0.85109982, 0.69456926]]])